### ISSUE TITLE
How can I add Cygwin platform?

### ISSUE THREAD

**Issue by daitangio** [ninenines/erlang.mk#274]
Hi, I'd like to push a bunch of code to add 
"CYGWIN_NT-6.1"
platform (or variant)
I think gnu platform is good, but I am unsure....

else ifeq ($(UNAME_S),CYGWIN_NT-6.1)
PLATFORM = gnu
else
$(error Unable to detect platform. Please open a ticket with the output of uname -a.)
endif

**Comment by essen** [comment]
In short: you can't. By that I mean you can surely add Cygwin in erlang.mk, but it won't work.

The issue comes from the fact that Erlang doesn't run inside Cygwin. There's only plain win32 support, not cygwin. So things like path handling fails horribly.

The first step would therefore be to make Erlang work on Cygwin if we want it to work there.

I have plans to move to Make 4 which would allow us to not require Unix tooling to do the same as we do today, however, so perhaps this would be something you would prefer too.

**Comment by daitangio** [comment]
I understand. So I cannot use erlan.mk on windows? It is a pity because I have a unix box, but on my daily work I use windows7 with cygwin and I hope to handle some erlang from there.

**Comment by essen** [comment]
Yeah unfortunately it's not easy. I am interested in porting Erlang to Cygwin if that's something you want to help with, but I won't be able to look into it until mid-summer due to important life events. :-)

The other option, moving to Make 4, would make it work in plain Windows, but in that case a great many projects will not "just work" due to them not being tested on plain Windows.

**Comment by essen** [comment]
Hey, you might be interested to know that I have added over the week-end MSYS2 support. Erlang.mk is also tested on Windows using a CI service and everything currently tested works (I'm having small issues documented in #363).

Closing this as it seems like it won't be necessary after all. :-)

Enjoy!

**Comment by daitangio** [comment]
Great! I will give you a try with cygwin to let you know....

**Comment by essen** [comment]
Cygwin won't work, for sure. MSYS2 only so far.

**Comment by daitangio** [comment]
MSYS2 stands for Microsoft unix-like-toolset?

**Comment by essen** [comment]
MSYS2 stands for MSYS2. See the installation document at: https://github.com/ninenines/erlang.mk/blob/master/doc/src/guide/installation.asciidoc#on-windows

It should be very easy to setup and get started. I also have most issues tested and fixed for MSYS2 now. Bigger one left is that the relx extended start script is a little weird and not always well behaving, which I will be fixing soon. Trying to get feedback as to how people use it (if anyone does). If you don't use releases, everything should be fine.

Feedback welcome!
