### ISSUE TITLE
Question re lager runtime opts

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#283]
(this is just a *question*, not an issue)

I've found it impossible to get lager to work without adding the following lines to my makefile

ERLC_COMPILE_OPTS= +'{parse_transform, lager_transform}'
ERLC_OPTS += $(ERLC_COMPILE_OPTS)

as per this issue:

http://stackoverflow.com/questions/25530298/lager-calls-failing-during-common-test-test-runs/25536760#25536760

assuming that a) I'm right; you do always need them and b) lager is a popular library for experienced devs and noobs alike, is there an argument for including these lines within erlang.mk ?

**Comment by essen** [comment]
Right you need the parse_transform option. That's true regardless of the build tool you use, it's a requirement from lager.

No need to have the intermediate variable though, you can just do:

ERLC_OPTS += +'{parse_transform, lager_transform}'

Lager is one of a number of logging solutions, the most popular one for sure, but by no means the only one. It would be a little weird to do something specific to one project, especially since we have no control over it and it might change in the future.

**Comment by jhw** [comment]
NP; thanks for the colour

**Comment by essen** [comment]
Closing, cheers!
