### ISSUE TITLE
Configurable Erlang bin path

### ISSUE THREAD

**Issue by Gatzy118** [ninenines/erlang.mk#289]
Hi, I think it would be really useful to be able to configure the Erlang bin path, e.g.

ERL_BIN = /path/to/erlang/bin

It would simply require changing every reference to erl, erlc, dialyzer etc. with $(ERL_BIN)/erl
And then potentially defaulting ERL_BIN like so:

ERL_BIN ?= $(dir $(shell which erl))

Unless there's a nicer way without having to shell out?

**Comment by essen** [comment]
PATH=/path/to/erlang/bin:$PATH make

Should do it.

**Comment by Gatzy118** [comment]
That's how we currently solve it but would prefer to set this in the project Makefile as it is more consistent with our builds for other languages. Most build systems allow the compiler to be set in the Makefile e.g. setting GCC= CXX= etc.

**Comment by essen** [comment]
You can also set PATH in the Makefile directly. :-)

I'm open to adding variables, but I need to understand what the use case is. I don't believe it's the same as CC= because that one is meant to switch compilers (or use the correct name when it changes between platforms), not hardcode their paths. So having an ERLC= variable would be about using something other than erlc, not setting its path, and I don't think such a thing exists.

**Comment by Gatzy118** [comment]
I agree regarding ERLC, and didn't realise the PATH could be modified from within the Makefile:

export PATH := /path/to/erlang/bin:$(PATH)

did the trick. Thanks very much!
