### ISSUE TITLE
turn {vsn, "git"} into a resonable tag

### ISSUE THREAD

**Issue by lehoff** [ninenines/erlang.mk#365]
Right now dependencies with {vsn, "git"} in the .app.src file ends up as dep-git in the lib dir in the release.

It would be nice if more saying thing that git was there.

Rebar uses the format: 

```
clique-0.3.3-1-gb971cef 
```

So it is the latest tag - number of commits - hash.

I know that one could end up with several of those after a while of heavy development, but that is something that one has to clean up when ready to release.
And I'd much rather see that things are moving than having a dep-git that changes without any indication to me.
I envision that one removes all the -x.y.z-w-hash directories before bundling a release.

If people do not have the discipline to do this it is their own problem.

**Comment by essen** [comment]
Yeah rebar does something similar to `git describe --dirty --abbrev=7 --tags --always --first-parent`. This is what we do if you put {id, "git"} in the .app.src currently (or if you remove the .app.src and use Makefile-based configuration).

For .app.src setups, we can add this detection on both vsn and id without much trouble and let users decide what they prefer.

For the "no .app.src" setup, perhaps the same could be done to vsn when we have `PROJECT_VERSION = git`. For id, we already add the git describe command automatically (though I need to disable it for the current non-dependency project).

**Comment by lehoff** [comment]
It would be good to have the id behaviour for vsn as well.
A lot easier than having to change a bunch of dependencies after first forking them just for this.

The "no .app.src" setup is tricky, but if we view it from the stand-point of a build master using it as a dependency then adding this behaviour would ease the burden. He/she probably has enough problems with wacky developers already.

**Comment by lehoff** [comment]
I have given this a bit of thought during the day. 

It might be nice if one could set a flag somehow to signal that one wants to set the vsn in the .app file to some git output _regardless_ of what is in the .app.src file.
This would work very for a development phase where potentially a lot of apps are being updated.

Come release time one should go for either {vsn, "x.y.z"} or {vsn, "git"} depending on ones temperament.

I don't see a bit issue in the .app.src file using {vsn, "git"} as it is a src file, so it is to be expected to be modified in the process of moving from src to ebin.

**Comment by essen** [comment]
Doesn't sound like it would be a problem.

**Comment by essen** [comment]
Writing down my thoughts on this:

I am against special casing "git". Instead it should be possible to define rules to run when a special keyword is found. In other words, not just "git".

When PROJECT_VERSION = git, Erlang.mk will replace the version number with the git describe, if any (empty if this isn't coming from a git repo). It does this because there will be something like app_version_git defined that has the git describe command in it.

Similarly, when PROJECT_VERSION = whatever, Erlang.mk will call app_version_whatever which returns whatever version it wants, and Erlang.mk replaces it in the .app file.

When PROJECT_VERSION = whatever AND app_version_whatever doesn't exist, then "whatever" is put as the version. This means that we can just do PROJECT_VERSION = 2.0.0-pre.3 and it will still work.

I believe something similar should be done for the `id` key, and a new variable PROJECT_ID should be added (defaulting to "git" though). Similarly, there should be app_id_git and so on to allow defining these. One could for example decide to take some metadata to put into the `id` key like build environment or whatever they fancy.

Thoughts?

**Comment by essen** [comment]
As for forcing the behavior onto dependencies we could for example have a "FORCE_PROJECT_VERSION = git" that would override PROJECT_VERSION regardless of its actual value.

**Comment by essen** [comment]
For rebar deps I think it makes sense that during autopatch the `{vsn, "git"}` is replaced with whatever git describe says. For Erlang.mk there's no need to do anything, you can just do `PROJECT_VERSION = $(shell git describe ...)`. I'll add the fix to autopatch later today/tomorrow.

**Comment by essen** [comment]
Done locally, push soon. Thanks!
