### ISSUE TITLE
bootstraped code fails to compile if parent dir has its name starting with caps

### ISSUE THREAD

**Issue by kansi** [ninenines/erlang.mk#400]
Following fails

```
$ mkdir Tmp && cd Tmp
$ make -f erlang.mk bootstrap
$ make
 DEPEND Tmp.d
 ERLC   Tmp_app.erl Tmp_sup.erl
 src/Tmp_app.erl:1: bad module declaration
 src/Tmp_app.erl:2: no module definition
 src/Tmp_app.erl:8: variable 'Tmp_sup' is unbound
 erlang.mk:4859: recipe for target 'ebin/Tmp.app' failed
 make[1]: *** [ebin/Tmp.app] Error 1
 erlang.mk:4709: recipe for target 'app' failed
 make: *** [app] Error 2
```

I know that erlangers don't name their apps with caps but I want erlang.mk to handle this case so that if someone learning erlang tries to deviate from this convention they shouldn't face issues.

**Comment by essen** [comment]
Thanks.

**Comment by binarin** [comment]
The same for folder with hyphens in the name. Maybe the `bootstrap` target should just fail when there is incorrect symbols in folder name.

**Comment by hachreak** [comment]
I have the same issue.
In my case it's generating a default template for `myapp_app.erl` and `myapp_sup.erl`.
But the problem, If  I undestood correctly, it's because my application is called like `my-app` and inside the generated code I have the module name without single quotes:
```erlang
-moduie(my-app).
```
In this case I expected it was:
```erlang
-moduie('my-app').
```

@essen What about quoting the module name in the templates [here](https://github.com/ninenines/erlang.mk/blob/master/plugins/bootstrap.mk#L116), [here](https://github.com/ninenines/erlang.mk/blob/master/plugins/bootstrap.mk#L82), [here](https://github.com/ninenines/erlang.mk/blob/master/plugins/bootstrap.mk#L89) and in every place it needed? :)

**Comment by essen** [comment]
Something like `my-app` is trickier because Erlang will consider the application name to be `my` and `app` the version. It's not a good idea to use these characters or try to support them, IMO.

I don't mind adding quoting, but it has to be done only if necessary, so that normal module names don't appear quoted.

**Comment by essen** [comment]
I'm now disallowing both dashes and uppercase characters in application names. Push soon. Thanks!
