### ISSUE TITLE
Allow semver for hex dependencies

### ISSUE THREAD

**Issue by elbrujohalcon** [ninenines/erlang.mk#495]
According to @ericmj, hex is semver. So, it would be nice to allow dependency versions to be specified in _semver mode_, such as:
```
dep_myapp = hex >= 0.2.0 and < 0.3.0
dep_otherapp = hex ~> 0.2.0
```

**Comment by essen** [comment]
I don't really see the point. Surely it's that way so that you can check if all applications can work together, and Erlang.mk is going to be more strict about that by not assuming semver and pointing out any difference. It's also not going to help for the planned "update" target since it will list regardless of semver.

Feel free to add this to a plugin, we can easily leave the basic hex support in Erlang.mk and let the plugin override the defaults.

**Comment by elbrujohalcon** [comment]
I'm not yet skilled enough to create a plug-in that modifies the way in which dependency resolution works for erlang.mk on hex deps without affecting the way it works for the rest of the dep-fetching mechanisms.
Can you give me some tips on how to do so?

**Comment by essen** [comment]
The fetch methods start here: https://github.com/ninenines/erlang.mk/blob/master/core/deps.mk#L459

If for example you create a dep_fetch_hex_semver variable with the commands to run for fetching, and then define `dep_cowboy = hex_semver ...` it will use your commands for fetching.

**Comment by essen** [comment]
Note that you can create this fetch method in the plugin and it will work as intended.

**Comment by elbrujohalcon** [comment]
Closing this issue in favor of inaka/hexer.mk#16
