### ISSUE TITLE
Question re deps of deps

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#528]
Not suggesting this is a bug, but would like to know why things work this way

I have a dependency ('child project') which itself has a number of git deps (eg syslog)

A parent project includes child project as a dep; the parent project does not of itself use syslog however

On making the parent project, syslog is pulled into deps and everything builds correctly. On 'make run: however the parent project fails because syslog isn't included in the top level release, unless I specify syslog as an additional dependency at the parent project level.

Why couldn't Erlang.mk detect that syslog should be included in the parent release ?

Or do I need to get better at distinguishing between build and runtime deps ?

Thanks!

**Comment by ingwinlu** [comment]
sounds like 'child project' is missing syslog as an application dependency in .app.src or similar

**Comment by jhw** [comment]
I should have said that child_project is a rebar project and syslog is
specified in rebar.config

Child project compiles and tests correctly with syslog on a standalone basis

When child_project is used as an Erlang.mk dep by parent_project, syslog
appears under parent_project deps (even though is not part of parent
project makefile) but does not make it into parent_project release

?

sounds like 'child project' is missing syslog as an application dependency
in .app.src or similar

—
Reply to this email directly or view it on GitHub
<https://github.com/ninenines/erlang.mk/issues/528#issuecomment-189614065>.

**Comment by essen** [comment]
If the child project has a .app.src file, then syslog also needs to be listed there, otherwise it can't be picked up automatically. Rebar projects are in that category, even if Erlang.mk can deal with rebar.config to fetch deps properly, it can't know which of the dependencies should be in the .app.src and therefore it is not touched. So if there is a .app.src file, check that syslog is listed there. Rebar.config only matters for fetching.

**Comment by jhw** [comment]
I need to add an app.src file. Thanks! Closed :-)
