### ISSUE TITLE
lighter erlang.mk?

### ISSUE THREAD

**Issue by benoitc** [ninenines/erlang.mk#537]
This is quite an open question, but I am wondering why the bootstrapped `erlang.mk` should contain a default list of package, where it could only contains the "build logic"?

Indeed I can understand the usefulness of having  a list of default packages but I really wish that my projects don't have to embed all these links to unused package when I ship them. Instead why not having them available in a separate repository and have a tool to fetch infos about them and generate a file that could then be included or used by erlang.mk?

Something like the [carthage file](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#cartfile) 

Thoughts?

**Comment by essen** [comment]
I am all for a proper package manager, but since we don't have that the workaround is to have the Erlang.mk package index. It's bundled for convenience (update Erlang.mk, update everything), but I suppose it doesn't need to be that way anymore.

As for how to specify dependencies, I don't think we need a separate file. What we have in the Makefile is already basically what is in this file so we don't win anything.

**Comment by crownedgrouse** [comment]
there is also another issue with the index embedded in erlang.mk. google search on a project return hundred links on projects that do not use this project, but only using erlang.mk. A gzipped separated index in a .erlang-mk directory could solve this.

**Comment by tsloughter** [comment]
With hex being adopted as the package manager by rebar3 and OTP why not accept it as the "proper package manager" for erlang.mk?

**Comment by essen** [comment]
Last I heard Hex was not adopted as the proper package manager for OTP.

**Comment by tsloughter** [comment]
Where did you hear that?

**Comment by essen** [comment]
Even if true, I have no plans to do anything until OTP does. I'm writing a build tool, not a package manager.

Currently we have a package index, and I'm OK with that, because ultimately it's just an alternative way of specifying deps. The index doesn't have to be bundled anymore so I suppose it will be only downloaded on demand in the future. The index is important for Erlang.mk development because the test suite goes through all packages to make sure Erlang.mk can compile them.

Package management on the other hand involves a lot more work. I have no plans to reimplement a package manager. If OTP adds an executable like erlhex then I have no problems using it. A couple people care about Hex and have written plugins so it's available. If there's more demand we could auto load them. But right now this doesn't seem necessary.

So at this point, wait and see.

**Comment by tsloughter** [comment]
That was sort of my point, currently you partially are writing a package manager, while hex does have a plugin for erlang.mk.

The hex client in OTP will likely simply be rebar3. But better for the community if build tools rallied around a common package manager now rather than waiting for merging into OTP. It takes a lot of time, which is why we started with just moving rebar3 to the erlang org instead of waiting until everything was ready to be merge-able, it better to get something going then waiting for all the stars to align.

**Comment by essen** [comment]
I'm not writing a package manager at all, not sure why you'd think so. The difference between using Erlang.mk packages vs using deps is that Erlang.mk gets the repository info in `pkg_$1_repository` instead of `dep_$1`. Calling it a package manager would be insulting to actual package managers.

Writing a package manager is not my fight. I have little interest in them, either as a user or a developer. I like my git repositories. But I have nothing against them either. Efforts just have to come from someone interested. I'll happily flick the auto load switch when there's enough demand.

**Comment by tsloughter** [comment]
That is why I said "partially". And you yourself call them packages and you "manage" them... 

And it isn't an issue of autoload the plugin but having it be the default way of fetching deps (the result of `DEPS = <name>`, instead of having to do `dep_<name> = hex <vsn>`. That would mean for the user declaring `<name>` in erlang.mk or rebar3 gets them the same result and further adoption of a package manager by the Erlang community.

**Comment by essen** [comment]
I'm not going to break useful functionality people rely on to further someone's political agenda. :-)

Maybe in a distant future Erlang.mk will look into Hex by default. But today is not the day. I have no plans to switch to an insecure fetch method when what we have so far works perfectly well.

I also wouldn't put too much weight on my choice of words for "package index". It's an index alright, but they're not packages in any sense of the term. "project index" or "dependency index" might be more appropriate.

**Comment by tsloughter** [comment]
I know they aren't packages, I said that the first time you called them packages :P
And it isn't insecure.....

Just trying to move Erlang dev tooling forward and not continue having a split when it comes to dependencies.

**Comment by essen** [comment]
The insecure part I know of is in the current plugins implementation, which doesn't check anything. With git, you got ssl and checksum automatically. With HTTP GET, nope. And that's not been implemented.

I also want to start signing commits soon and have automated check. I don't think there's support for that in Hex yet.

**Comment by benoitc** [comment]
I don't think having hex as a prefix is an issue. It's more a matter of doc. The nice thing is that if people want to use it it's here and it works. Maybe hex.pm could actually document the usage of erlang.mk like it does for rebar3?


@essen back of the original issue, what about adding the possibility to bootstrap erlang.mk without any package list by default? something like `make -f erlang.mk bootstrap_light` whatever the wording. I can send you a PR for it :)

**Comment by benoitc** [comment]
updated above s/is/is not

**Comment by essen** [comment]
Sounds good actually, as a first step. But make it `make -f erlang.mk bootstrap WITHOUT=index` as it leaves room for removing other optional parts if needed.

Note that the `WITHOUT=index` part is independent from the bootstrapping. When first downloaded, Erlang.mk is built from the git repository and you need to pass that to the Erlang.mk Makefile. I'll have time this week-end if needed.

**Comment by benoitc** [comment]
I will do with the option, very good idea :)

**Comment by benoitc** [comment]
I wanted to say `I don't think having hex as a prefix is an issue.` ie it's not an issue. Logic failed ...

**Comment by ericmj** [comment]
> Maybe hex.pm could actually document the usage of erlang.mk like it does for rebar3?

PRs appreciated and we already show erlang.mk example configs for packages.

**Comment by essen** [comment]
@benoitc Any luck? :-)

**Comment by benoitc** [comment]
i will send it tonight :)

**Comment by benoitc** [comment]
@essen ^^

**Comment by essen** [comment]
The PR was merged a while ago.
