### ISSUE TITLE
When not GNUmake, try something else

### ISSUE THREAD

**Issue by vanrein** [ninenines/erlang.mk#741]
I am calling Erlang.mk from CMake, which [introduces a bit of extra complexity](https://github.com/vanrein/perpetuum/blob/9f218ea194e21fe712ba4f710cf0ccc8d018a7e2/erlang/CMakeLists.txt#L38-L45).

Not all platforms run make as gmake (think of BSD, Mac OS X); not all platforms have a gmake (think of Linux).  As a result, there is no one way of invoking the desired command.  Then there is the matter of the gmake version.

Erlang.mk is sensitive about the version of make used, but is clever enough to run the test in lower-IQ versions of the tool.  Would the same logic be usable to detect if gmake is available, possibly in a newer version somewhere on the `$PATH`, and run that?  Needless to say that this raises a concern of endless recursion, but it would be rare and should be solved when version information is taken into account.  One might run the detected make on a Makefile with a very simple target, for instance: `/path/to/other/make_or_gmake -f erlang.mk are_you_up_to_this`

The alternative would be to chase for a proper version in CMake.  This is not a current use of `FindPackage()` that I have found but, more importantly, it is not ideal to place knowledge of Erlang.mk requirements in another (and in all other) packages that include it through CMake.

Why CMake?  Because it can build more than just Erlang, and is a great help in getting away from local variations of plain make on the various platforms.  Ideally, I would have liked Erlang.mk to be a CMake discipline, or pre-integerated with it.

**Comment by essen** [comment]
Sounds like this is something that should be solved in CMake? There's no way to detect BSD Make and switch for example since the erlang.mk file will just fail on BSD Make. And it's also not a very good idea to try to call a different Make than the one the user told us to run, it's unlikely to work everywhere and can lead to surprises at best.

Erlang.mk has GNU Make as part of its requirements so users are expected to run this, and the required version will be incremented to 4 soon (as opposed to having a warning telling users to upgrade).

**Comment by vanrein** [comment]
Hi Loïc,

It can be solved in CMake, yes.  It's not the most elegant place, that's all.  As with the other issue, I'm sharing what I think might be helpful to add power to Erlang.mk, in the hope that it is useful.

-Rick

**Comment by essen** [comment]
Elegance is subjective there. When the user calls GNU Make it creates a variable `$(MAKE)` that points to that executable, and Erlang.mk always uses that for subsequent invocations. That lets the user decide which executable should be called if they have more than one (like on OSX with Homebrew, or users of beta/development versions, in the PATH or not).

If it was a script then I'd get your point since those have more control over what will run them, but Makefiles are a different beast.
