### ISSUE TITLE
Conflicting dependency versions

### ISSUE THREAD

**Issue by goertzenator** [ninenines/erlang.mk#745]
I have an app that depends on cowboy-2.2.2, but also depends directly on ranch because I need to do some custom SSL handling for my cowboy server.  I *don't* specify a version on my ranch dep.

Cowboy-2.2.2 requires ranch-1.4.0, however erlang.mk quietly pulls in ranch-1.2.1 which causes cowboy to fail.  My work-around is to remove the unversioned ranch dep which then causes ranch-1.4.0 to be pulled in.

Dependency version specification and conflict is a thorny issue.  What happens when one app has genuine sub-dependencies on both ranch-1.2.1 and ranch-1.4.1?  The Rust folks have put a lot of discussion into this problem; I don't know what the resolution is but there may be pertinent discussion there.  I don't know what rebar does.

**Comment by crownedgrouse** [comment]
Only solution is to run each version in a different node, and applications talking together.  If Erlang had namespaces,  we could run same library in different versions and different libraries with same name at same time. Maybe some days

**Comment by essen** [comment]
There's an hex_erl project that is being worked on which will provide an Erlang interface to Hex. It will also come with dependency version resolution and I think using this will save us a lot of troubles because then for people who use only Hex dependencies they can be sure that the Hex dependencies are consistent (since Hex enforces it). This won't matter for other sources like git but it should at least be something.
