### ISSUE TITLE
Warnings as error not working for me?

### ISSUE THREAD

**Issue by greenbeanstree** [ninenines/erlang.mk#753]
so I'm aware warnings as error is on by default.

whenever I have syntax issues, I see also any warnings that are existing. When I only fix the syntax issues and not the warnings, and type 'make run', the warnings don't show and program runs.

so I'm kind of confused why that is the case when I'm expecting compilation errors. can someone help me? thank you!

**Comment by essen** [comment]
Warnings as errors only apply to the current application, not dependencies.

**Comment by greenbeanstree** [comment]
ah I see. That explains it. Thanks. I would like to apply warnings as errors to dependencies as well. How do I go about accomplishing this?

**Comment by essen** [comment]
You can't, it's made this way to avoid running into issues when third party deps are not maintained, it's a very common source of compilation errors when a new OTP version is released, in otherwise perfectly working project, due to how deprecation works.

What you *can* do however is run `make` in each of the deps you want to check warnings in. This can be done in a number of ways. If you have some CI set up make sure to have a step that only does `make`.

**Comment by greenbeanstree** [comment]
Gotcha. I will do those suggestions. Thanks for the help!
