### ISSUE TITLE
Add "make test-shell"

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#756]
Does like shell but with the paths correctly set for test modules.

**Comment by KrzysiekJ** [comment]
Why not just add `$(TEST_DIR)` to the default value of `SHELL_PATHS`? `make shell` currently does not build the application, so it should not be a big problem that it doesn’t also build tests. To run a shell on a clean directory, one will need just to run `make test-build shell` instead of `make app shell`.
