### ISSUE TITLE
"make COVER=1 eunit" fails in multi-app repository

### ISSUE THREAD

**Issue by rlipscombe** [ninenines/erlang.mk#781]
If I run `make COVER=1 eunit` in my multi-app repository, it runs all of the unit tests and then fails with:

```
/home/roger/Source/foo/erlang.mk:6591: recipe for target 'eunit' failed
make: *** [eunit] Error 1
```

If I patch in some extra logging to `erlang.mk`, it's failing on the `cover:compile_beam_directory("ebin")` line in the `eunit.erl` function, because it appears to be looking for an `ebin` directory at the top level. Which, obviously, doesn't exist.

**Comment by essen** [comment]
I got a fix for this but I have an additional question. It produces a coverdata file in each of the different apps/*, meaning you have to do the merging on your own later if necessary. Do you need all files from the different apps/* to be merged into one when you do `make all.coverdata` or is it better per application? I'm not using apps/* so any guidance as to how it should be improved is welcome.

Either way the fix for this is done locally and I'll push soon. Thanks!
